#!/bin/bash
#
# This script updates Lifemapper configuration file config/config.lmcompute.ini
# Run by the roll install process on all nodes of lmcompute cluster

usage () 
{
    echo "Usage: $0"
    echo "This script is run during the roll install it will:"
    echo "     - update config/config.lmcompute.ini file with values from LMdbserver and LM_webserver attributes "
    echo "     - add [machine] section to config/config.lmcompute.ini  "
    echo "     - add maintenance scripts to /etc/cron.daily/ directory  "
    echo "   "
}

# update permissions on config files
updatePerms () {
    GID=`grep lmwriter: /etc/group`
    if [ "$GID" != "" ] ; then
        chgrp  lmwriter @PKGROOT@/config/config*.ini*
        chmod g+ws @PKGROOT@/config/config*.ini*
    fi
}

# update linker paths
runLdconfig () {
    /sbin/ldconfig
}

# update config/config.lmcompute.ini
updateConfig () {
    @PKGROOT@/rocks/bin/updateIP-lmcompute
}

# install cron jobs for daily execution
installCronJobs () {
    @PKGROOT@/rocks/bin/installComputeCronJobs
}

# source Lifemapper env
setEnv () {
    PROF=/etc/profile.d/lmcompute.sh
    if [ -f $PROF ] ; then
	 . $PROF 
    else
    	echo "ERROR: file $PROF not found" 
    	exit
    fi
}

#### Main #####
if [ $# -ne 0 ]; then
    usage
    exit 0
fi

# run all updates
setEnv
runLdconfig
updateConfig 
installCronJobs
updatePerms
